export default [
  { comand: "menu" , resume: "Exibe o menu do dono"},
  { comand: "setList",resume: "Recebe o txt da lista de contatos" },
  { comand: "verLista",resume: "Busca e exibe lista pelo nome" },
  { comand: "apagarLista",resume: "Deleta uma lista" },
  { comand: "setKeyword",resume: "Recebe o txt da lista de keywords e suas respostas." },
  { comand: "verKeyword",resume: "Busca e exibe keyword pelo nome" },
  { comand: "verTodasKeywords",resume: "Mostra todas as keywords salvas" },  
  { comand: "apagarKeyword",resume: "Deleta uma keyword" },
  { comand: "setFluxo",resume: "Recebe o txt com uma lista de fluxo com perguntas e suas variáveis que serão armazenadas" },
  { comand: "verFluxo",resume: "Busca e exibe perguntas de um fluxo pelo nome" },
  { comand: "verTodosFluxos",resume: "Exibe todos os fluxos cadastrados." },
  { comand: "apagarFluxo",resume: "Deleta um fluxo pelo nome" },
  { comand: "verCliente",resume: "Busca e exibe um cliente" },
  { comand: "msgExtra",resume: "Exibe listas de extras salvas de determinado contato" },
  { comand: "disparo", resume: "Envia mensagem para a lista selecionada" },
  { comand: "disparoTemp", resume: "Envia mensagem para a lista selecionada em determinado horario" },
  { comand: "disparoFluxo", resume: "Envia fluxo selecionado para a lista selecionada" },
  { comand: "comandos", resume: "Exibe todos os comandos." },
];
