export default [
  { comand: "menu" , resume: "Exibe o menu do dono"},
  { comand: "setList",resume: "Recebe o txt da lista de contatos" },
  { comand: "verLista",resume: "busca e exibe lista pelo nome" },
  { comand: "apagarLista",resume: "deleta uma lista" },
  { comand: "setKeyword",resume: "recebe o txt da lista de keywords e suas respostas." },
  { comand: "verKeyword",resume: "busca e exibe keyword pelo nome" },
  { comand: "verTodasKeywords",resume: "mostra todas as keywords salvas" },  
  { comand: "apagarKeyword",resume: "deleta uma keyword" },
  { comand: "setFluxo",resume: "recebe o txt com uma lista de fluxo com perguntas e suas variáveis que serão armazenadas" },
  { comand: "verFluxo",resume: "busca e exibe perguntas de um fluxo pelo nome" },
  { comand: "verTodosFluxos",resume: "exibe todos os fluxos cadastrados." },
  { comand: "apagarFluxo",resume: "deleta um fluxo pelo nome" },
  { comand: "verCliente",resume: "busca e exibe um cliente" },
  { comand: "msgExtra",resume: "exibe listas de extras salvas de determinado contato" },
  { comand: "disparo", resume: "envia mensagem para a lista selecionada" },
  { comand: "disparoTemp", resume: "envia mensagem para a lista selecionada em determinado horario" },
  { comand: "disparoFluxo", resume: "envia fluxo selecionado para a lista selecionada" },
  { comand: "comandos", resume: "exibe todos os comandos." },
];
